3rd module completed
js-tasks-ru/js-20211109_necroorc pull request #3
Opened 2021-11-17 20:49 UTC by Armas0n

2021-11-17 20:50 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-18 18:47 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      .split('.')
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-11-18 18:47 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (!obj) return;
👍 good

2021-11-18 18:47 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let resultArr = [];
👍 good

2021-11-18 18:47 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr))
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2021-11-18 18:47 UTC, dosandk requested changes
необходимо поправить решение `createGetter`

2021-11-19 12:09 UTC, Armas0n commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr))
Set весьма непривычный для меня тип данных. Преимуществ нет, скорее я просто забыл, что спред работает и на Сеты в том числе

2021-11-19 12:16 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-19 15:46 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)]
можно использовать и `Array.from`, в чем разница обсудим на занятии

2021-11-19 15:46 UTC, dosandk approved these changes
good 👍

2021-11-19 15:47 UTC, merged